version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: jewelry_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_DATABASE: jewelry_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: jewelry_redis
    ports:
      - "6379:6379"

volumes:
  mariadb_data:
